name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Update README
      env:
        WAKATIME_TOKEN: ${{ secrets.WAKATIME_USER }}
      run: |-
        python -m wakatime > README.md
        cat README.md

    - name: Commit and push if changed
      run: |-
        git diff
        git config --global user.email "readme-bot@example.com"
        git config --global user.name "README-bot"
        git commit -am "Updated content" || exit 0
        git push
